# Generated by Django 5.0 on 2024-05-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='in_person',
            field=models.BooleanField(default=False, verbose_name='In Person'),
        ),
        migrations.AddField(
            model_name='user',
            name='virtual',
            field=models.BooleanField(default=False, verbose_name='Virtual'),
        ),
    ]
