# Generated by Django 5.0 on 2024-06-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jon_company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Empresa / II.EE.'),
        ),
    ]
