# Generated by Django 5.0 on 2024-08-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_certificate_alter_user_credential_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_networking',
            field=models.BooleanField(default=False, verbose_name='Allow Networking'),
        ),
    ]
