# Generated by Django 5.0 on 2024-08-27 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0002_alter_companysettings_logo'),
        ('users', '0009_alter_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_customers', to='conf.country'),
        ),
    ]
