# Generated by Django 5.0 on 2024-09-21 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='jon_company',
            new_name='job_company',
        ),
    ]
