from django.urls import path
from .views import (
    HomeView, EventsView, GenerateCredentialView, validate_register,
    confirm_register, SelectPreferencesView, TicketView, LogoutView,
    save_preferences_answers, AfterCreatedCredentialView, CustomerCredential,
    login_access, EventTransmissionView, CustomerTicket, SuccessSurveyView,
    SurveyView, save_survey_answers, allow_networking_user, NetworkingView,
    save_networking_preferences, NetworkingUsersView, RecoverPasswordView,
    ScheduledEventsView, TicketViewPDF, ResetPasswordView, CertificateView,
    CloseLandingView, GenerateCertificateView, BlogListView, BlogDetailView,
    DownloadCustomerTicket, ConfirmUser, ValidateInPersonCompanyUser,
    CommunityView, GenerateUserCommunityPreference, WhiteView,
    GenerateInvitedEmail, GetVoteCategoryStatus, VoteView, save_vote_answers,
    save_accepted_additional_terms
)
from rest_framework.routers import DefaultRouter


router = DefaultRouter()

app_name = 'landing'

urlpatterns = [
     path('', HomeView.as_view(), name='home'),
     path('evento/', EventsView.as_view(), name='event'),
     path('transmision/<slug>/', EventTransmissionView.as_view(), name='transmission'), # noqa
     path('logout/', LogoutView.as_view(), name='logout'),
     path('validate_register/', validate_register, name='validate_register'),
     path('confirm_register/', confirm_register, name='confirm_register'),
     path('login_access/', login_access, name='login_access'),
     path('generar-credencial/',
          GenerateCredentialView.as_view(), name='generate_credential'),
     path('after-generated/<uid>/',
          AfterCreatedCredentialView.as_view(), name='credential_generated'),
     path('preferencias/',
          SelectPreferencesView.as_view(), name='select_preferences'),
     path('ticket/',
          TicketView.as_view(), name='ticket_view'),
     path('save_preferences_answers/', save_preferences_answers,
          name='save_preferences_answers'),
     path('download-credential-image/<uid>/',
          CustomerCredential.as_view(), name='download_credential'),
     path('download-customer-ticket/', CustomerTicket.as_view(),
          name='download_customer_ticket'),
     path('encuesta/',
          SurveyView.as_view(), name='survey_view'),
     path('encuesta-culminada/',
          SuccessSurveyView.as_view(), name='finished_survey'),
     path('save_survey_answers/', save_survey_answers,
          name='save_survey_answers'),
     path('allow_networking_user/', allow_networking_user,
          name='allow_networking_user'),
     path('networking-preferencias/', NetworkingView.as_view(),
          name='networking_preferences'),
     path('save_networking_preferences/', save_networking_preferences,
          name='save_networking_preferences'),
     path('networking/', NetworkingUsersView.as_view(),
          name='networking'),
     path('comunidades/', CommunityView.as_view(),
          name='community'),
     path('recover-password/',
          RecoverPasswordView.as_view(), name="recover_password"),
     path('agendados/',
          ScheduledEventsView.as_view(), name='scheduled_events'),
     path('reset-password/<uuid>/',
          ResetPasswordView.as_view(), name="reset_password"),
     # path('ticket-pdf/',
     #      TicketViewPDF.as_view(), name='ticket_view_pdf'),
     path('certificate/',
          CertificateView.as_view(), name='certificate'),
     path('fin/', CloseLandingView.as_view(), name='closed'),
     path('generar-certificado/',
          GenerateCertificateView.as_view(), name="generate_certificate"),
     path('blog/',
          BlogListView.as_view(), name="blog"),
     path('blog-detail/<slug>/',
          BlogDetailView.as_view(), name='blog_detail'),
     path('download_ticket/<hash_id>',
          DownloadCustomerTicket.as_view(), name='download_ticket'),
     path('confirmation_user/<hash_id>',
          ConfirmUser.as_view(), name='confirmation_user'),
     path('validate_in_person/',
          ValidateInPersonCompanyUser.as_view(), name='validate_in_person'),
     path('generate_cummunity_preference/',
          GenerateUserCommunityPreference.as_view(),
          name='generate_cummunity_preference'),
     path(
          'generate_invited/', GenerateInvitedEmail.as_view(),
          name='generate_invited'),
     path(
          'api/vote_category/get_vote_category/',
          GetVoteCategoryStatus.as_view(),
          name='get_vote_category'),
     path(
          'vote_category/<slug>/',
          VoteView.as_view(), name='vote_category'),
     path('save_vote_answers/', save_vote_answers,
          name='save_vote_answers'),
     path('save_accepted_additional_terms/', save_accepted_additional_terms,
          name='save_accepted_additional_terms'),
]
urlpatterns += router.urls
