# Generated by Django 5.0 on 2024-04-21 19:20

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='in_person',
            field=models.BooleanField(default=False, verbose_name='In Person'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_virtual',
            field=models.BooleanField(default=False, verbose_name='Is virtual'),
        ),
        migrations.AddField(
            model_name='company',
            name='main_event_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Main event datetime'),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('home_banner', models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='Home Banner')),
                ('home_video_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Home Video Url')),
                ('first_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='First Title')),
                ('main_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Main Title')),
                ('secondary_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Secondary Title')),
                ('main_event_description', models.TextField(blank=True, verbose_name='Main Event Description')),
                ('main_event_subtitle', models.CharField(blank=True, max_length=255, verbose_name='Main Event Subtitle')),
                ('main_event_video_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Main Event Video Url')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_company', to='companies.company')),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Pages',
            },
        ),
        migrations.CreateModel(
            name='ItemMainEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Posición')),
                ('main_description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='description')),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_event_items', to='companies.homepage')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ('position',),
            },
        ),
    ]
