# Generated by Django 5.0 on 2024-04-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_main_event_end_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='main_event_subtitle',
        ),
        migrations.AddField(
            model_name='homepage',
            name='main_event_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Main Event title'),
        ),
    ]
