# Generated by Django 5.0 on 2024-05-30 03:49

import src.apps.companies.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_company_is_private_alter_company_is_virtual'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='access_type',
            field=models.CharField(choices=[('IN_PERSON', 'In Person'), ('VIRTUAL', 'Virtual'), ('HYBRID', 'hybrid')], default=src.apps.companies.constants.AccessType['VIRTUAL'], max_length=30, verbose_name='access type'),
        ),
        migrations.AddField(
            model_name='company',
            name='allow_virtual_access',
            field=models.BooleanField(default=True, verbose_name='Allow virtual access'),
        ),
    ]
