# Generated by Django 5.0 on 2024-05-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_company_access_type_company_allow_virtual_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='capacity',
            field=models.PositiveIntegerField(default=500, verbose_name='Capacity'),
        ),
    ]
