# Generated by Django 5.0 on 2024-05-31 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_company_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='current_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Current quantity'),
        ),
    ]
