# Generated by Django 5.0 on 2024-05-31 04:36

import src.apps.companies.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_company_current_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='access_type',
            field=models.CharField(choices=[('IN_PERSON', 'IN PERSON'), ('VIRTUAL', 'VIRTUAL'), ('HYBRID', 'HYBRID')], default=src.apps.companies.constants.AccessType['VIRTUAL'], max_length=30, verbose_name='access type'),
        ),
    ]
