# Generated by Django 5.0 on 2024-06-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_company_access_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='test_bcp/company/', verbose_name='Logo'),
        ),
    ]
