# Generated by Django 5.0 on 2024-06-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='test_realvirtual/company/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='home_banner',
            field=models.ImageField(blank=True, null=True, upload_to='test_realvirtual/banner/', verbose_name='Home Banner'),
        ),
    ]
