# Generated by Django 5.0 on 2024-06-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_homepage_date_description_homepage_time_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='test_realvirtual/banner/', verbose_name='Banner'),
        ),
    ]
