# Generated by Django 5.0 on 2024-08-09 02:54

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_homepage_main_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto')),
                ('mobile', models.CharField(blank=True, max_length=255, null=True, verbose_name='Número teléfono')),
                ('facebook', models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, max_length=255, null=True, verbose_name='Twitter')),
                ('linkedin', models.URLField(blank=True, max_length=255, verbose_name='Linkedin')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footer', to='companies.company')),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footers',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('show_about_section', models.BooleanField(default=True, verbose_name='Mostrar Acerca de')),
                ('show_schedule_section', models.BooleanField(default=True, verbose_name='Mostrar Agenda')),
                ('show_gallery_section', models.BooleanField(default=True, verbose_name='Mostrar Galería')),
                ('show_sponsors_section', models.BooleanField(default=True, verbose_name='Mostrar Auspiciadores')),
                ('show_networking_section', models.BooleanField(default=True, verbose_name='Mostrar Networking')),
                ('show_survey_section', models.BooleanField(default=True, verbose_name='Mostrar Encuesta')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='header', to='companies.company')),
            ],
            options={
                'verbose_name': 'Header',
                'verbose_name_plural': 'Headers',
            },
        ),
    ]
