# Generated by Django 5.0 on 2024-08-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_header_show_more_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='show_exhibitors_section',
            field=models.BooleanField(default=True, verbose_name='Mostrar Expositores'),
        ),
    ]
