# Generated by Django 5.0 on 2024-08-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_company_use_filters_header_about_section_header_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='test_realvirtual/video_banner/', verbose_name='Video File Banner'),
        ),
    ]
