# Generated by Django 5.0 on 2024-08-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0024_header_login_title_header_register_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='sponsors_section_text',
            field=models.CharField(blank=True, default='Con la participación de', max_length=255, verbose_name='Auspiciadores texto'),
        ),
    ]
