# Generated by Django 5.0 on 2024-08-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0025_homepage_sponsors_section_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='networking_description_text',
            field=models.CharField(blank=True, default='Conéctate con los demás usuarios.', max_length=255, verbose_name='Networking descripción texto'),
        ),
    ]
