# Generated by Django 5.0 on 2024-08-22 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0026_alter_homepage_networking_description_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='use_rooms',
            field=models.BooleanField(default=False, verbose_name='Usa salas'),
        ),
        migrations.AddField(
            model_name='company',
            name='use_shifts',
            field=models.BooleanField(default=False, verbose_name='Usa turnos'),
        ),
        migrations.AddField(
            model_name='header',
            name='button_color',
            field=models.CharField(default='#008ac9', max_length=20, verbose_name='Header botón color'),
        ),
        migrations.AddField(
            model_name='header',
            name='button_text_color',
            field=models.CharField(default='#FFFFF', max_length=20, verbose_name='Header texto botón color'),
        ),
        migrations.AddField(
            model_name='header',
            name='header_color',
            field=models.CharField(default='#FFFFF', max_length=20, verbose_name='Header color'),
        ),
        migrations.AddField(
            model_name='header',
            name='header_text_color',
            field=models.CharField(default='#17181b', max_length=20, verbose_name='Header texto color'),
        ),
    ]
