# Generated by Django 5.0 on 2024-08-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0027_company_use_rooms_company_use_shifts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='test_realvirtual/favicon/', verbose_name='Favicon'),
        ),
    ]
