# Generated by Django 5.0 on 2024-08-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0028_company_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='buttons_color',
            field=models.CharField(default='#008ac9', max_length=20, verbose_name='Botones color'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='text_buttons_color',
            field=models.CharField(default='#FFFFFF', max_length=20, verbose_name='Texto en Botones color'),
        ),
    ]
