# Generated by Django 5.0 on 2024-08-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0029_homepage_buttons_color_homepage_text_buttons_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='use_dates',
            field=models.BooleanField(default=False, verbose_name='Usa fecha en lista'),
        ),
        migrations.AlterField(
            model_name='company',
            name='use_rooms',
            field=models.BooleanField(default=False, verbose_name='Usa salas en lista'),
        ),
    ]
