# Generated by Django 5.0 on 2024-08-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0030_company_use_dates_alter_company_use_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cookies_policy',
            field=models.FileField(blank=True, null=True, upload_to='test_realvirtual/documents/', verbose_name='Políticas Cookies'),
        ),
        migrations.AddField(
            model_name='company',
            name='privacy_policy',
            field=models.FileField(blank=True, null=True, upload_to='test_realvirtual/documents/', verbose_name='Políticas de privacidad'),
        ),
        migrations.AddField(
            model_name='company',
            name='protection_data_policy',
            field=models.FileField(blank=True, null=True, upload_to='test_realvirtual/documents/', verbose_name='Políticas de Protección de datos'),
        ),
        migrations.AddField(
            model_name='company',
            name='terms_and_conditions',
            field=models.FileField(blank=True, null=True, upload_to='test_realvirtual/documents/', verbose_name='Términos y condiciones'),
        ),
    ]
