# Generated by Django 5.0 on 2024-08-27 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0033_company_counter_datetime_company_counter_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='counter_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de contador'),
        ),
    ]
