# Generated by Django 5.0 on 2024-08-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0034_alter_company_counter_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='main_event_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre principal del evento'),
        ),
        migrations.AlterField(
            model_name='company',
            name='domain',
            field=models.CharField(max_length=255, unique=True, verbose_name='dominio'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre compañia'),
        ),
    ]
