# Generated by Django 5.0 on 2024-09-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0038_emailtemplate_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompany',
            name='allow_networking',
            field=models.BooleanField(default=False, verbose_name='Allow Networking'),
        ),
        migrations.AddField(
            model_name='usercompany',
            name='in_person',
            field=models.BooleanField(default=False, verbose_name='In Person'),
        ),
        migrations.AddField(
            model_name='usercompany',
            name='virtual',
            field=models.BooleanField(default=False, verbose_name='Virtual'),
        ),
    ]
