# Generated by Django 5.0 on 2024-09-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0040_alter_usercompany_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='confirm_user',
            field=models.BooleanField(default=False, verbose_name='Confirmar Usuarios'),
        ),
        migrations.AddField(
            model_name='company',
            name='enable_preferences',
            field=models.BooleanField(default=False, verbose_name='Habilitar selección de preferencias'),
        ),
    ]
