# Generated by Django 5.0 on 2024-09-11 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0041_company_confirm_user_company_enable_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompany',
            name='uuid_hash',
            field=models.CharField(blank=True, default='', help_text='Random UUID hash to recover password.', max_length=36, verbose_name='UUID'),
        ),
    ]
