# Generated by Django 5.0 on 2024-09-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0042_usercompany_uuid_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='message_confirm_user',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje confirmación'),
        ),
    ]
