# Generated by Django 5.0 on 2024-09-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0044_alter_company_message_confirm_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='contact_header_name',
            field=models.CharField(default='Contacto', max_length=50, verbose_name='Nombre Contacto Header'),
        ),
        migrations.AddField(
            model_name='header',
            name='register_form_text',
            field=models.TextField(default='Completa el siguiente formulario para poder registrar tus datos.', verbose_name='Texto Registro Formulario'),
        ),
        migrations.AddField(
            model_name='header',
            name='register_form_title',
            field=models.CharField(default='Crear cuenta', max_length=255, verbose_name='Título Registro Formulario'),
        ),
        migrations.AddField(
            model_name='header',
            name='show_contact',
            field=models.BooleanField(default=False, verbose_name='Mostrar Contacto en Header'),
        ),
        migrations.AlterField(
            model_name='header',
            name='register_title',
            field=models.CharField(default='Regístrate', max_length=50, verbose_name='Título Registro'),
        ),
    ]
