# Generated by Django 5.0 on 2024-09-13 00:15

import src.apps.companies.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0045_header_contact_header_name_header_register_form_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='css_fonts',
            field=models.CharField(choices=[('CSS_DMSANS', 'css-DMSans'), ('CSS_INTERTIGHT', 'css-Intertight')], default=src.apps.companies.constants.FontType['CSS_DMSANS'], max_length=30, verbose_name='Css Fonts'),
        ),
    ]
