# Generated by Django 5.0 on 2024-09-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0047_font_remove_company_css_fonts_company_font'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre carpeta Font'),
        ),
    ]
