# Generated by Django 5.0 on 2024-09-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0048_alter_font_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompany',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Es admin'),
        ),
    ]
