# Generated by Django 5.0 on 2024-09-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0049_usercompany_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_position_names_field_title',
            field=models.CharField(default='Cargo', max_length=100, verbose_name='Título Cargo en Formulario'),
        ),
        migrations.AddField(
            model_name='company',
            name='confirm_email_names_field_title',
            field=models.CharField(default='Confirmar Email', max_length=100, verbose_name='Título Confirmar Email en Formulario'),
        ),
        migrations.AddField(
            model_name='company',
            name='country_names_field_title',
            field=models.CharField(default='País', max_length=100, verbose_name='Título País en Formulario'),
        ),
        migrations.AddField(
            model_name='company',
            name='email_names_field_title',
            field=models.CharField(default='Email', max_length=100, verbose_name='Título Email en Formulario'),
        ),
        migrations.AddField(
            model_name='company',
            name='job_company_names_field_title',
            field=models.CharField(default='Empresa', max_length=100, verbose_name='Título Empresa en Formulario'),
        ),
        migrations.AddField(
            model_name='company',
            name='last_names_field_title',
            field=models.CharField(default='Apellidos', max_length=100, verbose_name='Título Apellidos en Formulario'),
        ),
        migrations.AddField(
            model_name='company',
            name='names_field_title',
            field=models.CharField(default='Nombres', max_length=100, verbose_name='Título Nombres en Formulario'),
        ),
        migrations.AddField(
            model_name='company',
            name='occupation_names_field_title',
            field=models.CharField(default='Profesión', max_length=100, verbose_name='Título Profesión en Formulario'),
        ),
    ]
