# Generated by Django 5.0 on 2024-09-21 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0051_company_code_body_company_code_header'),
        ('conf', '0002_alter_companysettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompany',
            name='company_position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cargo / Carrera'),
        ),
        migrations.AddField(
            model_name='usercompany',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_company_users', to='conf.country'),
        ),
        migrations.AddField(
            model_name='usercompany',
            name='document',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='document'),
        ),
        migrations.AddField(
            model_name='usercompany',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='conf.documenttype'),
        ),
        migrations.AddField(
            model_name='usercompany',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='usercompany',
            name='first_surname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='First surname'),
        ),
        migrations.AddField(
            model_name='usercompany',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='usercompany',
            name='jon_company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Empresa / II.EE.'),
        ),
        migrations.AddField(
            model_name='usercompany',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='usercompany',
            name='last_surname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last surname'),
        ),
        migrations.AddField(
            model_name='usercompany',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='mobile'),
        ),
        migrations.AddField(
            model_name='usercompany',
            name='names',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Names'),
        ),
        migrations.AddField(
            model_name='usercompany',
            name='occupation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Profesion '),
        ),
        migrations.AddField(
            model_name='usercompany',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='usercompany',
            name='speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='specialities_company_users', to='conf.speciality'),
        ),
    ]
