# Generated by Django 5.0 on 2024-09-21 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0052_usercompany_company_position_usercompany_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercompany',
            old_name='jon_company',
            new_name='job_company',
        ),
    ]
