# Generated by Django 5.0 on 2024-09-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0055_footer_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_position',
            field=models.BooleanField(default=True, verbose_name='Cargo / Carrera'),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.BooleanField(default=True, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='company',
            name='job_company',
            field=models.BooleanField(default=True, verbose_name='Empresa / II.EE.'),
        ),
        migrations.AddField(
            model_name='company',
            name='job_company_select',
            field=models.BooleanField(default=False, verbose_name='Empresa / II.EE. Select'),
        ),
        migrations.AddField(
            model_name='company',
            name='last_name',
            field=models.BooleanField(default=True, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='company',
            name='names',
            field=models.BooleanField(default=True, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='company',
            name='occupation',
            field=models.BooleanField(default=True, verbose_name='Profesión'),
        ),
        migrations.AddField(
            model_name='company',
            name='occupation_select',
            field=models.BooleanField(default=False, verbose_name='Profesión Select'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.BooleanField(default=False, verbose_name='Teléfono'),
        ),
    ]
