# Generated by Django 5.0 on 2024-09-26 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0057_jobcompany_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompany',
            name='job_company_select',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_company_company_users', to='companies.jobcompany', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='usercompany',
            name='occupation_select',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupation_company_users', to='companies.jobcompany', verbose_name='Profesion'),
        ),
    ]
