# Generated by Django 5.0 on 2024-09-26 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0058_usercompany_job_company_select_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompany',
            name='occupation_select',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupation_company_users', to='companies.occupation', verbose_name='Profesion'),
        ),
    ]
