# Generated by Django 5.0 on 2024-09-27 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0059_alter_usercompany_occupation_select'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcompany',
            options={'ordering': ['position', 'name'], 'verbose_name': 'Empresa de trabajo', 'verbose_name_plural': 'Empresas de trabajo'},
        ),
        migrations.AlterModelOptions(
            name='occupation',
            options={'ordering': ['position', 'name'], 'verbose_name': 'Profesión', 'verbose_name_plural': 'Profesiones'},
        ),
    ]
