# Generated by Django 5.0 on 2024-09-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0061_usercompany_created_usercompany_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompany',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='test_realvirtual/certificates/', verbose_name='certificate'),
        ),
    ]
