# Generated by Django 5.0 on 2024-10-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0062_usercompany_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='gallery_section_name',
            field=models.CharField(blank=True, default='Empresa', max_length=255, verbose_name='Galería nombre Sección'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='gallery_section_text',
            field=models.CharField(blank=True, default='Con la participación de', max_length=255, verbose_name='Galería texto'),
        ),
    ]
