# Generated by Django 5.0 on 2024-10-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0064_company_warning_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='message_closed_in_person_register',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje Cierre registro presencial'),
        ),
        migrations.AddField(
            model_name='company',
            name='title_closed_in_person_register',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titulo Cierre registro presencial'),
        ),
    ]
