# Generated by Django 5.0 on 2024-11-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0065_company_message_closed_in_person_register_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='close_banner',
            field=models.ImageField(blank=True, null=True, upload_to='test_realvirtual/banner/', verbose_name='Closed Banner'),
        ),
        migrations.AddField(
            model_name='company',
            name='close_landing',
            field=models.BooleanField(default=False, verbose_name='Cerrar Landing'),
        ),
        migrations.AddField(
            model_name='company',
            name='close_mobile_banner',
            field=models.ImageField(blank=True, null=True, upload_to='test_realvirtual/mobile_banner/', verbose_name='Closed Mobile Banner'),
        ),
    ]
