# Generated by Django 5.0 on 2024-12-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0066_company_close_banner_company_close_landing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompany',
            name='allow_certificate',
            field=models.BooleanField(default=False, verbose_name='Permitir certificado'),
        ),
    ]
