# Generated by Django 5.0 on 2025-08-08 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0067_usercompany_allow_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version de plantilla')),
            ],
            options={
                'verbose_name': 'Version de plantilla',
                'verbose_name_plural': 'Fonts',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_versions', to='companies.templateversion'),
        ),
    ]
