# Generated by Django 5.0 on 2025-08-08 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0068_templateversion_company_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templateversion',
            options={'verbose_name': 'Version de plantilla', 'verbose_name_plural': 'Versions de plantilla'},
        ),
    ]
