# Generated by Django 5.0 on 2025-08-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0069_alter_templateversion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='home_image_banner',
            field=models.ImageField(blank=True, null=True, upload_to='test_realvirtual/image_banner/', verbose_name='Home Image Banner'),
        ),
    ]
