# Generated by Django 5.0 on 2025-08-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0070_homepage_home_image_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='home_banner_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='test_realvirtual/banner_mobile/', verbose_name='Home Banner Mobile'),
        ),
    ]
