# Generated by Django 5.0 on 2025-08-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0071_homepage_home_banner_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='home_banner_mobile',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='home_image_banner',
        ),
        migrations.AddField(
            model_name='company',
            name='home_image_banner',
            field=models.ImageField(blank=True, null=True, upload_to='test_realvirtual/image_banner/', verbose_name='Image Banner'),
        ),
    ]
