# Generated by Django 5.0 on 2025-08-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0072_remove_homepage_home_banner_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='address_description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Address description'),
        ),
    ]
