# Generated by Django 5.0 on 2025-08-09 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0073_homepage_address_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='home_image_banner',
            new_name='image_banner',
        ),
    ]
