# Generated by Django 5.0 on 2025-08-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0074_rename_home_image_banner_company_image_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='banner_second_section',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sección Secundaria'),
        ),
        migrations.AddField(
            model_name='company',
            name='banner_second_section_image',
            field=models.ImageField(blank=True, null=True, upload_to='test_realvirtual/image_banner/', verbose_name='Imagen de Sección Secundaria'),
        ),
        migrations.AddField(
            model_name='company',
            name='banner_second_section_internal_image',
            field=models.ImageField(blank=True, null=True, upload_to='test_realvirtual/image_banner/', verbose_name='Imagen de Sección Secundaria'),
        ),
        migrations.AddField(
            model_name='company',
            name='banner_second_section_internal_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto interno de Sección Secundaria'),
        ),
        migrations.AddField(
            model_name='company',
            name='banner_second_section_internal_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Título interno de Sección Secundaria'),
        ),
        migrations.AlterField(
            model_name='company',
            name='close_banner',
            field=models.ImageField(blank=True, null=True, upload_to='test_realvirtual/banner/', verbose_name='Banner de cierre'),
        ),
        migrations.AlterField(
            model_name='company',
            name='close_mobile_banner',
            field=models.ImageField(blank=True, null=True, upload_to='test_realvirtual/mobile_banner/', verbose_name='Banner Mobile de cierre'),
        ),
    ]
