# Generated by Django 5.0 on 2025-08-09 23:29

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0075_company_banner_second_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Posición')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='test_realvirtual/module/', verbose_name='Imagen')),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_modules', to='companies.homepage')),
            ],
            options={
                'verbose_name': 'Item Module',
                'verbose_name_plural': 'Items Modules',
                'ordering': ('position',),
            },
        ),
    ]
