# Generated by Django 5.0 on 2025-08-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0076_itemmodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='modules_section_header_name',
            field=models.CharField(default='Módulos', max_length=20, verbose_name='Nombre Módulos Header'),
        ),
        migrations.AddField(
            model_name='header',
            name='show_modules_section',
            field=models.BooleanField(default=True, verbose_name='Mostrar Módulos'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='module_section_name',
            field=models.CharField(blank=True, default='Módulos', max_length=255, verbose_name='Módulos nombre Sección'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='module_section_text',
            field=models.TextField(blank=True, verbose_name='Módulos texto Sección'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='module_section_title',
            field=models.CharField(blank=True, default='Programas y Ponentes', max_length=255, verbose_name='Módulos título Sección'),
        ),
    ]
