# Generated by Django 5.0 on 2025-08-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0077_header_modules_section_header_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodule',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
