# Generated by Django 5.0 on 2025-08-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0078_alter_itemmodule_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='blog_header_name',
            field=models.CharField(default='Blog', max_length=20, verbose_name='Nombre Blog Header'),
        ),
        migrations.AddField(
            model_name='header',
            name='show_blog_section',
            field=models.BooleanField(default=True, verbose_name='Mostrar Blog'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blog_button_title',
            field=models.CharField(blank=True, default='Visitar Blog', max_length=255, verbose_name='Expositores título botón Sección'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blog_section_name',
            field=models.CharField(blank=True, default='NOVEDADES', max_length=255, verbose_name='Blog nombre Sección'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blog_section_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Expositores título Sección'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='exhibitors_section_title',
            field=models.CharField(blank=True, default='Conoce a los expositores', max_length=255, verbose_name='Expositores título Sección'),
        ),
    ]
