# Generated by Django 5.0 on 2025-08-10 18:15

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0079_header_blog_header_name_header_show_blog_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorsMainEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Posición')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título')),
                ('number', models.CharField(blank=True, default=1, null=True, verbose_name='Número')),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_event_indicators', to='companies.homepage')),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
                'ordering': ('position',),
            },
        ),
    ]
