# Generated by Django 5.0 on 2025-08-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0080_indicatorsmainevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='blog_button_title',
            field=models.CharField(blank=True, default='Visitar Blog', max_length=255, verbose_name='Blog título botón Sección'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='blog_section_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Blog título Sección'),
        ),
    ]
