# Generated by Django 5.0 on 2025-08-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0081_alter_homepage_blog_button_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='home_banner',
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='test_realvirtual/banner/', verbose_name='Banner'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_second_section',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sección Secundaria'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_second_section_image',
            field=models.ImageField(blank=True, null=True, upload_to='test_realvirtual/image_banner/', verbose_name='Imagen de Sección Secundaria'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_second_section_internal_image',
            field=models.ImageField(blank=True, null=True, upload_to='test_realvirtual/image_banner/', verbose_name='Imagen de Sección Secundaria'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_second_section_internal_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto interno de Sección Secundaria'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_second_section_internal_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Título interno de Sección Secundaria'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='image_banner',
            field=models.ImageField(blank=True, null=True, upload_to='test_realvirtual/image_banner/', verbose_name='Image Banner'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mobile_banner',
            field=models.ImageField(blank=True, null=True, upload_to='test_realvirtual/mobile_banner/', verbose_name='Mobile Banner'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='test_realvirtual/video_banner/', verbose_name='Video File Banner'),
        ),
    ]
