# Generated by Django 5.0 on 2025-08-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0082_remove_homepage_home_banner_homepage_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='main_event_sub_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Detalle Evento Subtítulo'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner_second_section_internal_image',
            field=models.ImageField(blank=True, null=True, upload_to='test_realvirtual/image_banner/', verbose_name='Imagen Interna de Sección Secundaria'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='main_event_description',
            field=models.TextField(blank=True, verbose_name='Detalle Evento Description'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='main_event_image',
            field=models.ImageField(blank=True, null=True, upload_to='test_realvirtual/main_event_image/', verbose_name='Detalle Evento image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='main_event_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Detalle Evento Título'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='main_event_video_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Detalle Evento Video Url'),
        ),
    ]
