# Generated by Django 5.0 on 2025-08-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0083_homepage_main_event_sub_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='test_realvirtual/company/', verbose_name='Logo'),
        ),
    ]
