# Generated by Django 5.0 on 2025-08-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0084_alter_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='final_image',
            field=models.ImageField(blank=True, null=True, upload_to='test_realvirtual/final_image/', verbose_name='Imagen Sección final'),
        ),
    ]
