# Generated by Django 5.0 on 2025-08-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0085_homepage_final_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='youtube',
            field=models.URLField(blank=True, max_length=255, verbose_name='Youtube'),
        ),
    ]
