# Generated by Django 5.0 on 2025-08-31 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0086_footer_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='frequently_questions_header_name',
            field=models.CharField(default='Preguntas Frecuentes', max_length=20, verbose_name='Nombre Preguntas Frecuentes Header'),
        ),
        migrations.AddField(
            model_name='header',
            name='show_frequently_questions_section',
            field=models.BooleanField(default=True, verbose_name='Mostrar Preguntas Frecuentes'),
        ),
        migrations.AddField(
            model_name='header',
            name='show_workshops_section',
            field=models.BooleanField(default=True, verbose_name='Mostrar Talleres'),
        ),
        migrations.AddField(
            model_name='header',
            name='workshops_header_name',
            field=models.CharField(default='Talleres', max_length=20, verbose_name='Nombre Talleres Header'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='frequently_questions_section_name',
            field=models.CharField(blank=True, default='Preguntas Frecuentes', max_length=255, verbose_name='Preguntas Frecuentes nombre Sección'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='workshop_section_image',
            field=models.ImageField(blank=True, null=True, upload_to='test_realvirtual/workshop_image/', verbose_name='Detalle Talleres image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='workshop_section_name',
            field=models.CharField(blank=True, default='Talleres', max_length=255, verbose_name='Talleres nombre Sección'),
        ),
    ]
