# Generated by Django 5.0 on 2025-08-31 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0087_header_frequently_questions_header_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='banner_footer_section_image',
            field=models.ImageField(blank=True, null=True, upload_to='test_realvirtual/image_banner/', verbose_name='Imagen de Sección Footer'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
