# Generated by Django 5.0 on 2025-08-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0088_company_banner_footer_section_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_footer_section_image',
            field=models.ImageField(blank=True, null=True, upload_to='test_realvirtual/image_banner/', verbose_name='Imagen de Sección Footer'),
        ),
    ]
