# Generated by Django 5.0 on 2025-08-31 22:26

import src.apps.companies.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0089_homepage_banner_footer_section_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='email_type',
            field=models.CharField(choices=[('REGISTER', 'Registro completado'), ('PASSWORD', 'Recuperar/Reestablecer contraseña'), ('SCHEDULE', 'Confirmación de agenda'), ('WORKSHOP', 'Confirmación de agenda taller')], default=src.apps.companies.constants.EmailType['REGISTER'], max_length=30, verbose_name='¿Para qué se usará el correo?'),
        ),
    ]
