# Generated by Django 5.0 on 2025-09-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0090_alter_emailtemplate_email_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contact_phone',
            field=models.CharField(default='Email', max_length=100, verbose_name='Número de contacto'),
        ),
    ]
