# Generated by Django 5.0 on 2025-09-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0091_company_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de contacto'),
        ),
    ]
