# Generated by Django 5.0 on 2025-09-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0092_alter_company_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_private_with_confirmation',
            field=models.BooleanField(default=False, verbose_name='Es privado con confirmación'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Es privado'),
        ),
    ]
