# Generated by Django 5.0 on 2025-09-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0093_company_is_private_with_confirmation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='speciality',
            field=models.BooleanField(default=False, verbose_name='Speciality'),
        ),
        migrations.AddField(
            model_name='company',
            name='speciality_names_field_title',
            field=models.CharField(default='Email', max_length=100, verbose_name='Título Especialidad en Formulario'),
        ),
    ]
