# Generated by Django 5.0 on 2025-09-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0094_company_speciality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='address_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address description'),
        ),
    ]
