# Generated by Django 5.0 on 2025-09-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0095_alter_homepage_address_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='linkedin_pixel',
            field=models.TextField(blank=True, null=True, verbose_name='Linkedin pixel'),
        ),
    ]
