# Generated by Django 5.0 on 2025-09-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0096_company_linkedin_pixel'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_second_section_file',
            field=models.FileField(blank=True, null=True, upload_to='test_realvirtual/image_banner/', verbose_name='Documento de Sección Secundaria'),
        ),
    ]
