# Generated by Django 5.0 on 2025-09-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0098_alter_emailtemplate_email_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='workshop_section_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Talleres URL Sección'),
        ),
    ]
