# Generated by Django 5.0 on 2025-09-06 21:23

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0099_homepage_workshop_section_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='filter_domain_user',
            field=models.BooleanField(default=False, verbose_name='Filtrar registro por dominio en correo'),
        ),
        migrations.AddField(
            model_name='company',
            name='message_filter_domain_user',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje Usuario filtrado'),
        ),
        migrations.CreateModel(
            name='FilterEmailDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre dominio')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_filtered_email_domains', to='companies.homepage')),
            ],
            options={
                'verbose_name': 'Dominio de correo',
                'verbose_name_plural': 'DominioS de corre0',
            },
        ),
    ]
