# Generated by Django 5.0 on 2025-09-07 23:31

import src.apps.companies.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0100_company_filter_domain_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filteremaildomain',
            options={'verbose_name': 'Dominio de correo', 'verbose_name_plural': 'Dominios de correo'},
        ),
        migrations.AddField(
            model_name='usercompany',
            name='hash_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hash id'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='email_type',
            field=models.CharField(choices=[('REGISTER', 'Registro completado'), ('CONFIRMED_REGISTER', 'Registro usuario confirmado'), ('TO_CONFIRM_USER', 'Usuario por confirmar'), ('PASSWORD', 'Recuperar/Reestablecer contraseña'), ('SCHEDULE', 'Confirmación de agenda'), ('WORKSHOP', 'Confirmación de agenda taller')], default=src.apps.companies.constants.EmailType['REGISTER'], max_length=30, verbose_name='¿Para qué se usará el correo?'),
        ),
    ]
