# Generated by Django 5.0 on 2025-09-08 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0101_alter_filteremaildomain_options_usercompany_hash_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filteremaildomain',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_filtered_email_domains', to='companies.company'),
        ),
    ]
