# Generated by Django 5.0 on 2025-09-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0102_alter_filteremaildomain_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='message_filter_found_domain_user',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje Usuario encontrado filtrado'),
        ),
    ]
