# Generated by Django 5.0 on 2025-09-10 00:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0103_company_message_filter_found_domain_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='register_form_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Mensaje Registro'),
        ),
    ]
