# Generated by Django 5.0 on 2025-09-13 21:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0104_alter_header_register_form_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='message_confirm_workshop',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Mensaje confirmación Taller'),
        ),
    ]
