# Generated by Django 5.0 on 2025-09-14 17:38

import ckeditor.fields
import src.apps.companies.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0105_company_message_confirm_workshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='message_confirm_waiting_list_workshop',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Taller - Mensaje de confirmación en lista de espera'),
        ),
        migrations.AlterField(
            model_name='company',
            name='message_confirm_workshop',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Taller - Mensaje de confirmación'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='email_type',
            field=models.CharField(choices=[('REGISTER', 'Registro completado'), ('CONFIRMED_REGISTER', 'Registro usuario confirmado'), ('TO_CONFIRM_USER', 'Usuario por confirmar'), ('PASSWORD', 'Recuperar/Reestablecer contraseña'), ('SCHEDULE', 'Evento / Horario Agendado'), ('WORKSHOP', 'Taller Agendado'), ('WORKSHOP_WAITING', 'Taller en lista de espera Agendado')], default=src.apps.companies.constants.EmailType['REGISTER'], max_length=30, verbose_name='¿Para qué se usará el correo?'),
        ),
    ]
