# Generated by Django 5.0 on 2025-09-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0106_company_message_confirm_waiting_list_workshop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorsmainevent',
            name='sufix',
            field=models.CharField(blank=True, default='0', null=True, verbose_name='Sufijo'),
        ),
    ]
