# Generated by Django 5.0 on 2025-09-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0107_indicatorsmainevent_sufix'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='title_filter_user',
            field=models.CharField(blank=True, default='Registro exitoso', max_length=128, null=True, verbose_name='Titulo usuario filtrado'),
        ),
    ]
