# Generated by Django 5.0 on 2025-09-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0108_company_title_filter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='show_vote_section',
            field=models.BooleanField(default=False, verbose_name='Mostrar Votación'),
        ),
        migrations.AddField(
            model_name='header',
            name='vote_header_name',
            field=models.CharField(default='Votación', max_length=20, verbose_name='Nombre Votación Header'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='vote_section_name',
            field=models.CharField(blank=True, default='Categorías', max_length=255, verbose_name='Votación nombre Sección'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='vote_section_text',
            field=models.CharField(blank=True, default='Premios Palmas', max_length=255, verbose_name='Votación texto'),
        ),
    ]
