# Generated by Django 5.0 on 2025-09-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0109_header_show_vote_section_header_vote_header_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Banner url'),
        ),
    ]
