# Generated by Django 5.0 on 2025-09-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0110_homepage_banner_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='button_color',
            field=models.CharField(default='#008ac9', max_length=20, verbose_name='Color de botones'),
        ),
        migrations.AddField(
            model_name='company',
            name='button_text_color',
            field=models.CharField(default='#FFFFF', max_length=20, verbose_name='Color de Textos en botones '),
        ),
        migrations.AddField(
            model_name='company',
            name='section_color',
            field=models.CharField(default='#FFFFF', max_length=20, verbose_name='Color de Textos en botones '),
        ),
    ]
