# Generated by Django 5.0 on 2025-09-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0111_company_button_color_company_button_text_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='section_color',
            field=models.CharField(default='#FFFFF', max_length=20, verbose_name='Color de Secciones'),
        ),
    ]
