# Generated by Django 5.0 on 2025-09-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0112_alter_company_section_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='communities_header_name',
            field=models.CharField(default='Comunidades', max_length=20, verbose_name='Nombre Comunidades Header'),
        ),
        migrations.AddField(
            model_name='header',
            name='show_communities_section',
            field=models.BooleanField(default=False, verbose_name='Mostrar Comunidades'),
        ),
    ]
