# Generated by Django 5.0 on 2025-09-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0113_header_communities_header_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='community_description_text',
            field=models.CharField(blank=True, default='Conéctate con los demás usuarios.', max_length=255, verbose_name='commuComunidadesnity descripción texto'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='community_section_name',
            field=models.CharField(blank=True, default='Comunidades', max_length=255, verbose_name='Comunidades nombre Sección'),
        ),
    ]
