# Generated by Django 5.0 on 2025-09-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0115_company_meta_description_company_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='meta_image',
            field=models.ImageField(blank=True, null=True, upload_to='test_realvirtual/meta_images/', verbose_name='Meta Imagen'),
        ),
    ]
