# Generated by Django 5.0 on 2025-10-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0116_company_meta_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='headquarters',
            field=models.BooleanField(default=True, verbose_name='País'),
        ),
    ]
