# Generated by Django 5.0 on 2025-10-29 03:35

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0117_company_headquarters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='headquarters',
        ),
        migrations.AddField(
            model_name='company',
            name='headquarter',
            field=models.BooleanField(default=True, verbose_name='Sede'),
        ),
        migrations.AddField(
            model_name='company',
            name='headquarter_names_field_title',
            field=models.CharField(default='Sede', max_length=100, verbose_name='Título Sede en Formulario'),
        ),
        migrations.CreateModel(
            name='Headquarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Posición')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headquarters', to='companies.company')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='usercompany',
            name='headquarter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headquarter_company_users', to='companies.headquarter'),
        ),
    ]
