# Generated by Django 5.0 on 2025-10-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0118_remove_company_headquarters_company_headquarter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='headquarter',
            field=models.BooleanField(default=False, verbose_name='Sede'),
        ),
    ]
