# Generated by Django 5.0 on 2025-10-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0119_alter_company_headquarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='phone_names_field_title',
            field=models.CharField(default='Teléfono', max_length=100, verbose_name='Título Teléfono en Formulario'),
        ),
    ]
