# Generated by Django 5.0 on 2025-11-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0120_company_phone_names_field_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='preferences_text',
            field=models.TextField(blank=True, null=True, verbose_name='Texto Preferencias'),
        ),
        migrations.AddField(
            model_name='company',
            name='preferences_title',
            field=models.CharField(blank=True, default='Ayúdanos a atenderte mejor', max_length=255, null=True, verbose_name='Título Preferencias'),
        ),
    ]
