# Generated by Django 5.0 on 2025-11-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0121_company_preferences_text_company_preferences_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='register_button_title',
            field=models.CharField(default='Enviar', max_length=100, verbose_name='Registro título botón'),
        ),
    ]
