# Generated by Django 5.0 on 2025-11-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0122_header_register_button_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompany',
            name='aditional_terms',
            field=models.BooleanField(default=False, verbose_name='Acepta condiciones adicionales'),
        ),
    ]
