# Generated by Django 5.0 on 2025-11-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0123_usercompany_aditional_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='additonal_terms',
            field=models.FileField(blank=True, null=True, upload_to='test_realvirtual/documents/', verbose_name='Términos Adicionales'),
        ),
    ]
