# Generated by Django 5.0 on 2025-11-08 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0124_company_additonal_terms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='additonal_terms',
            new_name='additional_terms',
        ),
    ]
