# Generated by Django 5.0 on 2025-11-08 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0125_rename_additonal_terms_company_additional_terms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercompany',
            old_name='aditional_terms',
            new_name='additional_terms',
        ),
    ]
