# Generated by Django 5.0 on 2025-11-10 14:59

import src.apps.companies.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0126_rename_aditional_terms_usercompany_additional_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompany',
            name='accepted_additional_terms',
            field=models.CharField(choices=[('BLANK', 'No decidido'), ('ACCEPTED', 'Acapetado'), ('REJECTED', 'Rechazado')], default=src.apps.companies.constants.Status['BLANK'], max_length=30, verbose_name='Acepta condiciones adicionales'),
        ),
    ]
