# Generated by Django 5.0 on 2025-11-10 15:01

import src.apps.companies.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0127_usercompany_accepted_additional_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompany',
            name='accepted_additional_terms',
            field=models.CharField(choices=[('BLANK', 'Not decided'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default=src.apps.companies.constants.Status['BLANK'], max_length=30, verbose_name='Acepta condiciones adicionales'),
        ),
    ]
