# Generated by Django 5.0 on 2025-11-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0128_alter_usercompany_accepted_additional_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='communities_text',
            field=models.TextField(default='Selecciona una comunidad de tu interés', verbose_name='Texto interno Comunidades'),
        ),
    ]
