# Generated by Django 5.0 on 2024-05-15 01:47

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0006_remove_itemmainevent_main_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Posición')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sponsors', verbose_name='Imagen')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Video URL')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='companies.company')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Posición')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sponsors', verbose_name='Imagen')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='companies.company')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
