# Generated by Django 5.0 on 2024-05-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_alter_sponsor_options_alter_video_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='video_url',
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL'),
        ),
    ]
