# Generated by Django 5.0 on 2024-06-05 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_company_access_type'),
        ('landing', '0006_templatephoto_templatetoimage_credentialcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatephoto',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_photos', to='companies.company'),
        ),
    ]
