# Generated by Django 5.0 on 2024-06-06 01:46

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_company_access_type'),
        ('landing', '0007_templatephoto_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('title_credential', models.CharField(max_length=255, null=True, verbose_name='Titulo credencial')),
                ('image_credential', models.ImageField(blank=True, null=True, upload_to='credential', verbose_name='Imagen Fondo')),
                ('html_code', models.TextField(blank=True, verbose_name='Código HTML')),
                ('zoom', models.PositiveIntegerField(default=1, verbose_name='Zoom')),
                ('crop_h', models.PositiveIntegerField(default=0, verbose_name='Crop-h')),
                ('crop_w', models.PositiveIntegerField(default=0, verbose_name='Crop-w')),
                ('crop_x', models.PositiveIntegerField(default=0, verbose_name='Crop-x')),
                ('crop_y', models.PositiveIntegerField(default=0, verbose_name='Crop-y')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_photos', to='companies.company')),
            ],
            options={
                'verbose_name': 'Configuración de Credencial',
                'verbose_name_plural': 'Configuraciones de Credencial',
            },
        ),
        migrations.RemoveField(
            model_name='templatephoto',
            name='company',
        ),
        migrations.DeleteModel(
            name='TemplateToImage',
        ),
        migrations.DeleteModel(
            name='TemplatePhoto',
        ),
    ]
