# Generated by Django 5.0 on 2024-06-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_credentialcustomer_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialsettings',
            name='default_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Default Avatar'),
        ),
    ]
