# Generated by Django 5.0 on 2024-06-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_question_choicequestion_useranswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicequestion',
            name='sentence',
        ),
        migrations.AddField(
            model_name='choicequestion',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
    ]
