# Generated by Django 5.0 on 2024-06-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_remove_choicequestion_sentence_choicequestion_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicequestion',
            name='image',
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='icons', verbose_name='Imagen'),
        ),
    ]
