# Generated by Django 5.0 on 2024-06-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0013_remove_choicequestion_image_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='icons', verbose_name='Imagen icon'),
        ),
    ]
