# Generated by Django 5.0 on 2024-06-07 04:53

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_company_access_type'),
        ('landing', '0014_alter_question_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('event_date', models.CharField(max_length=255, null=True, verbose_name='Fecha evento')),
                ('event_name', models.CharField(max_length=255, null=True, verbose_name='Hora evento')),
                ('additional_information', models.CharField(max_length=255, null=True, verbose_name='Información adicional')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_ticket_settings', to='companies.company')),
            ],
            options={
                'verbose_name': 'Configuración de Ticket',
                'verbose_name_plural': 'Configuraciones de Ticket',
            },
        ),
    ]
