# Generated by Django 5.0 on 2024-06-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0017_ticketsettings_event_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialcustomer',
            name='credential_img',
            field=models.ImageField(blank=True, null=True, upload_to='test_realvirtual/credentials/', verbose_name='credential'),
        ),
        migrations.AlterField(
            model_name='credentialcustomer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='test_realvirtual/profile_img/', verbose_name='Imagen Perfil'),
        ),
        migrations.AlterField(
            model_name='credentialsettings',
            name='default_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='test_realvirtual/avatars/', verbose_name='Default Avatar'),
        ),
        migrations.AlterField(
            model_name='credentialsettings',
            name='image_credential',
            field=models.ImageField(blank=True, null=True, upload_to='test_realvirtual/credentials_backgrounds/', verbose_name='Imagen Fondo'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='test_realvirtual/icons/', verbose_name='Imagen icon'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='test_realvirtual/sponsors/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='test_realvirtual/videos/', verbose_name='Imagen'),
        ),
    ]
