# Generated by Django 5.0 on 2024-08-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0023_networkingoption_usernetworkingpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('image', models.ImageField(upload_to='test_realvirtual/free_images/', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Free Image',
                'verbose_name_plural': 'Free Images',
            },
        ),
    ]
