# Generated by Django 5.0 on 2024-08-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0024_freeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeimage',
            name='image',
            field=models.FileField(upload_to='test_realvirtual/free_images/', verbose_name='Imagen'),
        ),
    ]
