# Generated by Django 5.0 on 2024-08-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0026_alter_credentialsettings_title_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialsettings',
            name='first_text_message',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Primer mensaje Exito'),
        ),
        migrations.AddField(
            model_name='credentialsettings',
            name='second_text_message',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Segundo mensaje Exito'),
        ),
    ]
