# Generated by Django 5.0 on 2024-09-28 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0061_usercompany_created_usercompany_is_active_and_more'),
        ('landing', '0028_question_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernetworkingpreference',
            name='user',
        ),
        migrations.AddField(
            model_name='usernetworkingpreference',
            name='user_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='networkin_preferences', to='companies.usercompany'),
        ),
    ]
