# Generated by Django 5.0 on 2024-09-29 23:24

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0062_usercompany_certificate'),
        ('landing', '0029_remove_usernetworkingpreference_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CerficateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('image', models.FileField(blank=True, null=True, upload_to='test_realvirtual/credentials_backgrounds/', verbose_name='Imagen Fondo')),
                ('fonts', models.FileField(blank=True, null=True, upload_to='test_realvirtual/certificate_fonts/', verbose_name='Tipo Fuente')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_certifiate_settings', to='companies.company', unique=True)),
            ],
            options={
                'verbose_name': 'Certicate settings',
                'verbose_name_plural': 'Certicate settings',
            },
        ),
    ]
