# Generated by Django 5.0 on 2024-09-29 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0030_cerficatesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cerficatesettings',
            options={'verbose_name': 'Configuración de Certificado', 'verbose_name_plural': 'Configuraciones de Certificado'},
        ),
    ]
