# Generated by Django 5.0 on 2025-08-10 00:18

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0078_alter_itemmodule_description'),
        ('landing', '0031_alter_cerficatesettings_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('image', models.FileField(upload_to='test_realvirtual/blog_image/', verbose_name='Imagen')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='companies.company')),
            ],
            options={
                'get_latest_by': 'modified_date',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogPostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Posición')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido')),
                ('image', models.FileField(blank=True, null=True, upload_to='test_realvirtual/blog_image/', verbose_name='Imagen')),
                ('url_video', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL Video')),
                ('blog_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_post_items', to='companies.company')),
            ],
            options={
                'get_latest_by': 'modified_date',
                'abstract': False,
            },
        ),
    ]
