# Generated by Django 5.0 on 2025-08-10 00:28

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0078_alter_itemmodule_description'),
        ('landing', '0032_blogpost_blogpostitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Publicación para blog', 'verbose_name_plural': 'Publicaciones para blog'},
        ),
        migrations.AlterModelOptions(
            name='blogpostitem',
            options={'verbose_name': 'Item para publicación', 'verbose_name_plural': 'Items para publicación'},
        ),
        migrations.CreateModel(
            name='BlogPostItemContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Posición')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('blog_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_post_contents', to='companies.company')),
            ],
            options={
                'verbose_name': 'Contenido para publicación',
                'verbose_name_plural': 'Contenidos para publicación',
            },
        ),
    ]
