# Generated by Django 5.0 on 2025-08-10 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0033_alter_blogpost_options_alter_blogpostitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostitem',
            name='blog_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_post_items', to='landing.blogpost'),
        ),
        migrations.AlterField(
            model_name='blogpostitemcontent',
            name='blog_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_post_contents', to='landing.blogpost'),
        ),
    ]
