# Generated by Django 5.0 on 2025-08-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0034_alter_blogpostitem_blog_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='banner_image',
            field=models.FileField(blank=True, null=True, upload_to='test_realvirtual/blog_image/', verbose_name='Imagen banner'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='front_image',
            field=models.FileField(blank=True, null=True, upload_to='test_realvirtual/blog_image/', verbose_name='Imagen portada'),
        ),
    ]
