# Generated by Django 5.0 on 2025-08-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0035_remove_blogpost_image_blogpost_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fecha'),
        ),
    ]
