# Generated by Django 5.0 on 2025-08-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0036_blogpost_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='publish_date',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='Fecha de publicación'),
        ),
    ]
