# Generated by Django 5.0 on 2025-08-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0037_blogpost_publish_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('publish_date',), 'verbose_name': 'Publicación para blog', 'verbose_name_plural': 'Publicaciones para blog'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=450, verbose_name='Url'),
        ),
    ]
