# Generated by Django 5.0 on 2025-08-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0038_alter_blogpost_options_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostitem',
            name='image_video',
            field=models.FileField(blank=True, null=True, upload_to='test_realvirtual/blog_image/', verbose_name='Imagen Video'),
        ),
    ]
