# Generated by Django 5.0 on 2025-08-31 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0040_frequentlyquestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequentlyquestion',
            options={'verbose_name': 'Pregunta frecuente', 'verbose_name_plural': 'Preguntas frecuentes'},
        ),
    ]
