# Generated by Django 5.0 on 2025-09-06 18:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0041_alter_frequentlyquestion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequentlyquestion',
            name='answer',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Respuesta'),
        ),
    ]
