# Generated by Django 5.0 on 2025-09-17 03:43

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0109_header_show_vote_section_header_vote_header_name_and_more'),
        ('landing', '0042_alter_frequentlyquestion_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Posición')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descripción')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_vote_categories', to='companies.company')),
            ],
            options={
                'verbose_name': 'Categoria para votación',
                'verbose_name_plural': 'Categorias para votación',
            },
        ),
    ]
