# Generated by Django 5.0 on 2025-09-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0043_votecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='votecategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=450, verbose_name='Url'),
        ),
    ]
