# Generated by Django 5.0 on 2025-09-23 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0045_community_usercommunitypreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='position',
            field=models.PositiveIntegerField(default=1, verbose_name='Posición'),
        ),
    ]
