# Generated by Django 5.0 on 2025-10-01 02:55

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0116_company_meta_image'),
        ('landing', '0046_community_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votecategory',
            options={'verbose_name': 'Votación - Categoria', 'verbose_name_plural': 'Votación - Categorias'},
        ),
        migrations.AddField(
            model_name='votecategory',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Datetime'),
        ),
        migrations.AddField(
            model_name='votecategory',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Datetime'),
        ),
        migrations.CreateModel(
            name='VoteQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('position', models.SmallIntegerField(default=1, verbose_name='Posición')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('title', models.CharField(default='Elige un regalo', max_length=255, verbose_name='Titulo')),
                ('image', models.FileField(blank=True, null=True, upload_to='test_realvirtual/icons/', verbose_name='Imagen icon')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_vote_questions', to='companies.company')),
                ('vote_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_vote_questions', to='landing.votecategory')),
            ],
            options={
                'verbose_name': 'Votación - Pregunta',
                'verbose_name_plural': 'Votación -Preguntas',
                'ordering': ['company', 'position'],
            },
        ),
        migrations.CreateModel(
            name='VoteChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('position', models.SmallIntegerField(default=1, verbose_name='Posición')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_choice_questions', to='landing.votequestion')),
            ],
            options={
                'verbose_name': 'Votación - Opción',
                'verbose_name_plural': 'Votación - Opciones',
                'ordering': ['position', '-modified'],
            },
        ),
        migrations.CreateModel(
            name='VoteUserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('choice_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_vote_choice_questions', to='landing.votechoicequestion')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_vote_answers', to='companies.company')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_vote_questions', to='landing.votequestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vote_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Votación - Respuesta de Usuario',
                'verbose_name_plural': 'Votación - Respuestas de Usuario',
                'ordering': ['-modified'],
            },
        ),
    ]
