# Generated by Django 5.0 on 2025-10-01 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0047_alter_votecategory_options_votecategory_end_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteuseranswer',
            name='vote_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_category_answers', to='landing.votecategory'),
        ),
    ]
