# Generated by Django 5.0 on 2025-10-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0048_voteuseranswer_vote_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='votechoicequestion',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='test_realvirtual/icons/', verbose_name='Imagen icon'),
        ),
    ]
