# Generated by Django 5.0 on 2025-10-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0049_votechoicequestion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinvitedlanding',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customerinvitedlanding',
            name='first_surname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='first surname'),
        ),
        migrations.AlterField(
            model_name='customerinvitedlanding',
            name='last_surname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='last surname'),
        ),
        migrations.AlterField(
            model_name='customerinvitedlanding',
            name='names',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='names'),
        ),
    ]
