# Generated by Django 5.0 on 2025-10-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0050_alter_customerinvitedlanding_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='open_question',
            field=models.BooleanField(default=False, verbose_name='Es pregunta Abierta'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='open_answer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Respuesta Abierta'),
        ),
    ]
