# Generated by Django 5.0 on 2025-11-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0051_question_open_question_useranswer_open_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='required_open_question',
            field=models.BooleanField(default=True, verbose_name='Es pregunta abierta requerida'),
        ),
    ]
