# Generated by Django 5.0 on 2025-11-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0052_question_required_open_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='cerficatesettings',
            name='letter_color',
            field=models.CharField(default='#fff', verbose_name='Color de letra'),
        ),
    ]
