# Generated by Django 5.0 on 2025-11-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0053_cerficatesettings_letter_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='cerficatesettings',
            name='padding_top',
            field=models.CharField(default='1200px', verbose_name='Padding top'),
        ),
    ]
