# Generated by Django 5.0 on 2024-06-07 20:30

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import src.apps.tickets.mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0011_alter_company_access_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('code', models.CharField(blank=True, default='', max_length=8, verbose_name='Código del ticket')),
                ('qr', models.ImageField(blank=True, null=True, upload_to='tickets/qrcode', verbose_name='Qr')),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('document', models.CharField(blank=True, max_length=15)),
                ('full_name', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(blank=True, choices=[('f', 'borrador'), ('c', 'comprado'), ('e', 'enviado'), ('u', 'usado')], default='f', max_length=1)),
                ('description', models.CharField(blank=True, max_length=45, null=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Valor Unitario del ticket', max_digits=8, verbose_name='Valor')),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('seat', models.CharField(blank=True, max_length=20)),
                ('seat_section', models.CharField(blank=True, max_length=50)),
                ('is_invitation', models.BooleanField(default=False)),
                ('number_used_code', models.PositiveIntegerField(default=0, verbose_name='Numero de usos')),
                ('max_number_uses', models.PositiveIntegerField(default=0, verbose_name='Numero máximo de usos')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_tickets', to='companies.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified_date',
                'abstract': False,
            },
            bases=(src.apps.tickets.mixins.UidMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TicketUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('used_date', models.DateField(blank=True, null=True, verbose_name='Dia Usado')),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_uses', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Uso de ticket',
                'verbose_name_plural': 'Usos de ticket',
            },
        ),
    ]
