# Generated by Django 5.0 on 2024-06-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='tickets/pdf', verbose_name='PDF'),
        ),
    ]
