# Generated by Django 5.0 on 2024-06-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='test_realvirtual/tickets/pdf/', verbose_name='PDF'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='test_realvirtual/tickets/qrcode/', verbose_name='Qr'),
        ),
    ]
