# Generated by Django 5.0 on 2025-09-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='hash_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hash id'),
        ),
    ]
