# Generated by Django 5.0 on 2024-03-11 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('has_newsletters', models.BooleanField(default=False, verbose_name='has newsletters?')),
                ('has_accept_terms_conditions', models.BooleanField(default=True, verbose_name='accept term & conditions?')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Confirmado')),
                ('is_guest', models.BooleanField(default=False, verbose_name='is guest?')),
                ('confirm_code', models.CharField(max_length=255, null=True, verbose_name='Codigo de confirmacion')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-modified'],
            },
            bases=('users.user',),
        ),
    ]
