# Generated by Django 5.0 on 2024-05-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ('start_time',), 'verbose_name': 'Horario', 'verbose_name_plural': 'Horarios'},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='position',
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='End time'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Start time'),
        ),
    ]
