# Generated by Django 5.0 on 2024-06-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options_alter_schedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to='test_realvirtual/main_image/', verbose_name='Imagen Principal'),
        ),
        migrations.AlterField(
            model_name='exhibitor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='test_realvirtual/exhibitors/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='test_realvirtual/schedules/', verbose_name='Imagen'),
        ),
    ]
