# Generated by Django 5.0 on 2024-06-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_main_img_alter_exhibitor_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sub title'),
        ),
    ]
