# Generated by Django 5.0 on 2024-06-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL'),
        ),
    ]
