# Generated by Django 5.0 on 2024-08-17 20:11

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_header_show_exhibitors_section'),
        ('events', '0011_exhibitor_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleCustomerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_customer_schedules', to='companies.company')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_customers', to='events.event', verbose_name='Evento')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_customers', to='events.schedule', verbose_name='Schedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Horario Agendado',
                'verbose_name_plural': 'Horarios Agendados',
                'ordering': ['-modified'],
            },
        ),
    ]
