# Generated by Django 5.0 on 2024-08-20 04:14

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_schedulecustomerevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.PositiveIntegerField(default=1, verbose_name='Posición'),
        ),
        migrations.AddField(
            model_name='filter',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='filter',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active?'),
        ),
        migrations.AddField(
            model_name='filter',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='filter',
            name='position',
            field=models.PositiveIntegerField(default=1, verbose_name='Posición'),
        ),
    ]
