# Generated by Django 5.0 on 2024-08-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_category_options_alter_filter_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='categories',
        ),
        migrations.AddField(
            model_name='schedule',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='category_eventos', to='events.category'),
        ),
    ]
