# Generated by Django 5.0 on 2024-08-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_remove_event_categories_schedule_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='filter_name',
            field=models.SlugField(blank=True, max_length=450, verbose_name='Filter name'),
        ),
        migrations.AddField(
            model_name='filter',
            name='filter_name',
            field=models.SlugField(blank=True, max_length=450, verbose_name='Filter name'),
        ),
    ]
