# Generated by Django 5.0 on 2024-08-22 01:54

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_category_filter_name_filter_filter_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Posición')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('filter_name', models.SlugField(blank=True, max_length=450, verbose_name='Filter name')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Posición')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('filter_name', models.SlugField(blank=True, max_length=450, verbose_name='Filter name')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='room_schedules', to='events.room'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shift_schedules', to='events.shift'),
        ),
    ]
