# Generated by Django 5.0 on 2024-08-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_room_shift_schedule_room_schedule_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='flag_image',
            field=models.ImageField(blank=True, null=True, upload_to='test_realvirtual/flags/', verbose_name='Bandera Imagen'),
        ),
    ]
