# Generated by Django 5.0 on 2024-08-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_exhibitor_flag_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='name_on_list',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre en lista'),
        ),
    ]
