# Generated by Django 5.0 on 2024-09-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_exhibitor_name_on_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='ics_file',
            field=models.FileField(blank=True, null=True, upload_to='test_realvirtual/ics_files/', verbose_name='ICS File'),
        ),
    ]
