# Generated by Django 5.0 on 2024-09-13 03:53

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0048_alter_font_name'),
        ('events', '0020_schedule_ics_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulecustomerevent',
            name='user',
        ),
        migrations.AddField(
            model_name='schedulecustomerevent',
            name='company_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_user_schedules', to='companies.usercompany'),
        ),
        migrations.AlterField(
            model_name='schedulecustomerevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_event_company_users', to='events.event', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='schedulecustomerevent',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_company_users', to='events.schedule', verbose_name='Schedule'),
        ),
        migrations.CreateModel(
            name='CustomerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('company_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_user_events', to='companies.usercompany')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event_company_users', to='events.event')),
            ],
            options={
                'verbose_name': 'Asistencias de usuario',
                'verbose_name_plural': 'Asistencia de usuario',
                'ordering': ['-modified'],
            },
        ),
    ]
