# Generated by Django 5.0 on 2024-09-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_remove_schedulecustomerevent_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='link_title',
            field=models.CharField(blank=True, default='Ver perfil en Linkedin', max_length=255, verbose_name='Título Link'),
        ),
    ]
