# Generated by Django 5.0 on 2024-09-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_schedule_schedule_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_file',
            field=models.FileField(blank=True, null=True, upload_to='test_realvirtual/schedule_files/', verbose_name='File'),
        ),
    ]
