# Generated by Django 5.0 on 2025-08-31 00:37

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0086_footer_youtube'),
        ('events', '0025_alter_schedule_schedule_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Posición')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Título')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('image', models.ImageField(blank=True, null=True, upload_to='test_realvirtual/workshops/', verbose_name='Imagen')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_workshops', to='companies.company')),
                ('exhibitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exhibitor_workshops', to='events.exhibitor')),
            ],
            options={
                'verbose_name': 'Taller',
                'verbose_name_plural': 'Tallers',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('company_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_user_workshops', to='companies.usercompany')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workshop_company_users', to='events.workshop')),
            ],
            options={
                'verbose_name': 'Inscripción a taller',
                'verbose_name_plural': 'Inscripciones a talleres',
                'ordering': ['-modified'],
            },
        ),
    ]
