# Generated by Django 5.0 on 2025-08-31 00:42

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0086_footer_youtube'),
        ('events', '0026_workshop_workshopevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='ics_file',
            field=models.FileField(blank=True, null=True, upload_to='test_realvirtual/ics_files/', verbose_name='ICS File'),
        ),
        migrations.CreateModel(
            name='ScheduleCustomerWorkshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_schedule_workshops', to='companies.company')),
                ('company_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_user_workshops', to='companies.usercompany')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workshop_company_users', to='events.workshop')),
            ],
            options={
                'verbose_name': 'Inscripción a taller',
                'verbose_name_plural': 'Inscripciones a talleres',
                'ordering': ['-modified'],
            },
        ),
        migrations.DeleteModel(
            name='WorkshopEvent',
        ),
    ]
