# Generated by Django 5.0 on 2025-08-31 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_workshop_ics_file_schedulecustomerworkshop_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshop',
            options={'ordering': ['position', 'name'], 'verbose_name': 'Taller', 'verbose_name_plural': 'Talleres'},
        ),
    ]
