# Generated by Django 5.0 on 2025-08-31 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_alter_workshop_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Datetime'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Datetime'),
        ),
    ]
