# Generated by Django 5.0 on 2025-09-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_workshop_end_datetime_workshop_start_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='is_principal',
            field=models.BooleanField(default=False, verbose_name='Es principal'),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='text_is_principal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto Principal'),
        ),
    ]
