# Generated by Django 5.0 on 2025-09-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_exhibitor_is_principal_exhibitor_text_is_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='capacity',
            field=models.PositiveIntegerField(default=100, verbose_name='Capacidad'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='enrolled',
            field=models.PositiveIntegerField(default=0, verbose_name='Inscritos'),
        ),
    ]
