# Generated by Django 5.0 on 2025-09-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_workshop_capacity_workshop_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='principal_use',
            field=models.BooleanField(default=False, verbose_name='Uso principal'),
        ),
        migrations.AddField(
            model_name='filter',
            name='secondary_use',
            field=models.BooleanField(default=False, verbose_name='Uso secundario'),
        ),
    ]
