# Generated by Django 5.0 on 2025-09-13 00:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_filter_principal_use_filter_secondary_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
