# Generated by Django 5.0 on 2025-09-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_alter_schedule_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulecustomerworkshop',
            name='confirmed',
            field=models.BooleanField(default=True, verbose_name='Confirmado'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='waiting_list_capacity',
            field=models.PositiveIntegerField(default=0, verbose_name='Capacidad Lista de espera'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='waiting_list_enrolled',
            field=models.PositiveIntegerField(default=0, verbose_name='Inscritos Lista de espera'),
        ),
    ]
