# Generated by Django 5.0 on 2025-09-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_schedulecustomerworkshop_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección'),
        ),
    ]
