# Generated by Django 5.0 on 2025-09-19 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_workshop_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='allow_schedule',
            field=models.BooleanField(default=True, verbose_name='Permitir agendar'),
        ),
    ]
