# Generated by Django 5.0 on 2024-09-08 02:53

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import src.apps.chat.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0020_schedule_ics_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('client', models.CharField(blank=True, max_length=255, verbose_name='Cliente')),
                ('code', models.CharField(max_length=255, verbose_name='Codigo')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nombre')),
                ('chat_type', models.CharField(choices=[('EVENT', 'Para evento en vivo'), ('USERS', 'Para usuarios solamente')], default=src.apps.chat.constants.ChatType['EVENT'], max_length=30, verbose_name='Tipo de uso')),
                ('public', models.BooleanField(default=False, verbose_name='Es publico')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='events.event')),
            ],
            options={
                'get_latest_by': 'modified_date',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat_images/', verbose_name='Imagen')),
                ('names', models.CharField(max_length=255, verbose_name='Nombre')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='chat.chat')),
            ],
            options={
                'get_latest_by': 'modified_date',
                'abstract': False,
            },
        ),
    ]
