# Generated by Django 5.0 on 2024-03-11 21:47

import django.contrib.postgres.fields
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Posición')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='code')),
            ],
            options={
                'verbose_name': 'Rango de edad',
                'verbose_name_plural': 'Rangos de edad',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='CompanyPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='code')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre Cliente')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Logo')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='Email de contacto')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='teléfono')),
                ('ruc', models.CharField(blank=True, max_length=255, verbose_name='RUC')),
                ('fiscal_address', models.CharField(blank=True, max_length=255, verbose_name='dirección fiscal')),
                ('domain', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL del dominio')),
                ('contact_email', models.CharField(blank=True, max_length=255, verbose_name='email para contacto')),
                ('info_email', models.CharField(blank=True, max_length=255, verbose_name='email Info')),
                ('info_phone', models.CharField(blank=True, max_length=255, verbose_name='Telefono Info')),
                ('info_facebook', models.CharField(blank=True, max_length=255, verbose_name='Facebook Info')),
                ('info_instagram', models.CharField(blank=True, max_length=255, verbose_name='Instagram Info')),
                ('info_twitter', models.CharField(blank=True, max_length=255, verbose_name='Twitter Info')),
                ('info_pinterest', models.CharField(blank=True, max_length=255, verbose_name='Pinterest Info')),
                ('extra_settings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Posición')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='code')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Paises',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='code')),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documento',
            },
        ),
        migrations.CreateModel(
            name='LandingForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None, verbose_name='fields')),
                ('names', models.BooleanField(default=True, verbose_name='Nombres')),
                ('phone', models.BooleanField(default=False, verbose_name='Número de telefono')),
                ('address', models.BooleanField(default=False, verbose_name='Dirección')),
                ('gender', models.BooleanField(default=False, verbose_name='Género')),
                ('document_type', models.BooleanField(default=False, verbose_name='Tipo de documento')),
                ('document', models.BooleanField(default=False, verbose_name='N de documento')),
                ('date_birth', models.BooleanField(default=False, verbose_name='Fecha de Nacimiento')),
                ('occupation', models.BooleanField(default=False, verbose_name='Cargo ocupacional')),
                ('age_range', models.BooleanField(default=False, verbose_name='Rango de edad')),
                ('profile_image', models.BooleanField(default=False, verbose_name='Foto de perfil')),
                ('country', models.BooleanField(default=False, verbose_name='Pais')),
            ],
            options={
                'verbose_name': 'Formulario Registro',
                'verbose_name_plural': 'Formulario Registro',
                'ordering': ['-modified'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('code', models.CharField(blank=True, max_length=255, verbose_name='code')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Posición')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Speciality',
                'verbose_name_plural': 'Specialities',
            },
        ),
    ]
